// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

import {LibRaindexV6Released} from "./LibRaindexV6Released.sol";

import {LibRaindexV6SubParserReleased} from "./LibRaindexV6SubParserReleased.sol";

import {LibRouteProcessor4Released} from "./LibRouteProcessor4Released.sol";

import {LibGenericPoolRaindexV6ArbOrderTakerReleased} from "./LibGenericPoolRaindexV6ArbOrderTakerReleased.sol";

import {LibRouteProcessorRaindexV6ArbOrderTakerReleased} from "./LibRouteProcessorRaindexV6ArbOrderTakerReleased.sol";

import {LibGenericPoolRaindexV6FlashBorrowerReleased} from "./LibGenericPoolRaindexV6FlashBorrowerReleased.sol";

/// @title LibReleasedSuites
/// @notice Every frozen release this repo has cut, of every contract it
/// deploys: the per-contract released libs concatenated, in declaration
/// order.
///
/// There is one released lib per deployed contract because a release freezes
/// every contract it names into a single tag directory, so a lib that took
/// the record whole would give another contract's snapshot this contract's
/// suite key and collide with its own entry for that tag. This is where
/// those libs meet, and it is emitted from the same list that wrote them --
/// so a contract that is generated, aliased and frozen cannot be missing
/// from the declaration, and a release missing from the declaration is a
/// release every check quietly stops asking about.
library LibReleasedSuites {
    /// Every released suite, in declaration order.
    /// @return The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory) {
        DeploySuite[][] memory released = new DeploySuite[][](6);
        released[0] = LibRaindexV6Released.releasedSuites();
        released[1] = LibRaindexV6SubParserReleased.releasedSuites();
        released[2] = LibRouteProcessor4Released.releasedSuites();
        released[3] = LibGenericPoolRaindexV6ArbOrderTakerReleased.releasedSuites();
        released[4] = LibRouteProcessorRaindexV6ArbOrderTakerReleased.releasedSuites();
        released[5] = LibGenericPoolRaindexV6FlashBorrowerReleased.releasedSuites();

        uint256 total = 0;
        for (uint256 i = 0; i < released.length; i++) {
            total += released[i].length;
        }

        DeploySuite[] memory suites = new DeploySuite[](total);

        uint256 offset = 0;
        for (uint256 i = 0; i < released.length; i++) {
            for (uint256 j = 0; j < released[i].length; j++) {
                suites[offset + j] = released[i][j];
            }
            offset += released[i].length;
        }

        return suites;
    }
}
