// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

import {
    DEPLOYED_ADDRESS as RaindexV6_0_1_14_DEPLOYED_ADDRESS,
    BYTECODE_HASH as RaindexV6_0_1_14_BYTECODE_HASH,
    CREATION_CODE as RaindexV6_0_1_14_CREATION_CODE,
    RUNTIME_CODE as RaindexV6_0_1_14_RUNTIME_CODE,
    DEPENDENCIES as RaindexV6_0_1_14_DEPENDENCIES
} from "../generated/0_1_14/RaindexV6.sol";

import {
    DEPLOYED_ADDRESS as RaindexV6_0_1_15_DEPLOYED_ADDRESS,
    BYTECODE_HASH as RaindexV6_0_1_15_BYTECODE_HASH,
    CREATION_CODE as RaindexV6_0_1_15_CREATION_CODE,
    RUNTIME_CODE as RaindexV6_0_1_15_RUNTIME_CODE,
    DEPENDENCIES as RaindexV6_0_1_15_DEPENDENCIES
} from "../generated/0_1_15/RaindexV6.sol";

/// @title LibRaindexV6Released
/// @notice Every frozen release of `RaindexV6`: one entry per file in
/// the append-only `src/generated/<tag>/` record, in tag order.
///
/// The deploy address, code hash, creation code, runtime code and dependency
/// list of each entry are aliased from that release's own frozen snapshot, so
/// what a release deployed, and what it required to already be on chain, are
/// read from the immutable file and from nowhere else. A dependency dropped
/// from current source stays required by the releases cut with it, and one
/// added is not imposed on releases cut without it.
///
/// The key and the artifact path are explorer and ordering metadata
/// regenerated from the CURRENT declaration, and are not part of that
/// record. A moved source path retroactively updates every entry's artifact
/// path, which is intended: the alternative is parsing this generated file
/// back in to preserve what it last said.
library LibRaindexV6Released {
    /// Every frozen release, in tag order.
    /// @return The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory) {
        DeploySuite[] memory suites = new DeploySuite[](2);
        suites[0] = DeploySuite({
            suite: "raindex@0_1_14",
            creationCode: RaindexV6_0_1_14_CREATION_CODE,
            storedDeployedAddress: RaindexV6_0_1_14_DEPLOYED_ADDRESS,
            storedBytecodeHash: RaindexV6_0_1_14_BYTECODE_HASH,
            storedRuntimeCode: RaindexV6_0_1_14_RUNTIME_CODE,
            artifactPath: "src/concrete/raindex/RaindexV6.sol:RaindexV6",
            dependencies: abi.decode(RaindexV6_0_1_14_DEPENDENCIES, (address[]))
        });
        suites[1] = DeploySuite({
            suite: "raindex@0_1_15",
            creationCode: RaindexV6_0_1_15_CREATION_CODE,
            storedDeployedAddress: RaindexV6_0_1_15_DEPLOYED_ADDRESS,
            storedBytecodeHash: RaindexV6_0_1_15_BYTECODE_HASH,
            storedRuntimeCode: RaindexV6_0_1_15_RUNTIME_CODE,
            artifactPath: "src/concrete/raindex/RaindexV6.sol:RaindexV6",
            dependencies: abi.decode(RaindexV6_0_1_15_DEPENDENCIES, (address[]))
        });
        return suites;
    }
}
