[package]
name = "raindex_cli"
description = "Raindex CLI."
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { workspace = true }
raindex_common = { workspace = true }
raindex_app_settings = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ['env-filter'] }
url.workspace = true
flate2 = "1.0.34"
rusqlite = { version = "0.32", features = ["functions"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["full"] }

[target.'cfg(target_family = "wasm")'.dependencies]
tokio = { workspace = true, features = [
  "sync",
  "macros",
  "io-util",
  "rt",
  "time",
] }

[dev-dependencies]
tempfile.workspace = true
