// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Vm} from "forge-std-1.16.1/src/Test.sol";
import {IERC20} from "@openzeppelin-contracts-5.6.1/token/ERC20/IERC20.sol";
import {RaindexV6FreshTakeOrderTest} from "test/util/abstract/RaindexV6FreshTakeOrderTest.sol";
import {LibTestTakeOrder} from "test/util/lib/LibTestTakeOrder.sol";
import {
    OrderV4,
    IOV2,
    TakeOrderConfigV4,
    TakeOrdersConfigV5,
    TaskV2,
    IRaindexV6
} from "raindex-interface-0.1.1/src/interface/IRaindexV6.sol";
import {SignedContextV1} from "rain-interpreter-interface-0.1.0/src/interface/deprecated/v1/IInterpreterCallerV2.sol";
import {Float, LibDecimalFloat} from "rain-math-float-0.1.1/src/lib/LibDecimalFloat.sol";
import {LibOrder} from "../../../src/lib/LibOrder.sol";
import {MinimumIO, TokenMismatch} from "../../../src/concrete/raindex/RaindexV6.sol";
import {RecordingTaker} from "test/util/concrete/RecordingTaker.sol";

/// @title RaindexV6TakeOrderFreshMutationTest
/// @notice Adversarial-mutation coverage of the takeOrders4 take/skip loop run
/// against a FRESH-COMPILED RaindexV6 (see RaindexV6FreshTakeOrderTest) so that
/// mutations to src/concrete/raindex/RaindexV6.sol are observed. The committed
/// suite etches generated bytecode and is blind to source edits.
///
/// Token convention throughout: the order's INPUT token (what it receives) is
/// iToken0 and is the TAKER's OUTPUT (taker pays it via transferFrom); the
/// order's OUTPUT token (what it gives) is iToken1 and is the TAKER's INPUT
/// (taker receives it via transfer). `io.outputToken == iToken1`,
/// `io.inputToken == iToken0`.
contract RaindexV6TakeOrderFreshMutationTest is RaindexV6FreshTakeOrderTest {
    using LibDecimalFloat for Float;

    address internal alice = address(uint160(uint256(keccak256("alice.rain.test"))));
    address internal carol = address(uint160(uint256(keccak256("carol.rain.test"))));
    address internal bob = address(uint160(uint256(keccak256("bob.rain.test"))));

    bytes32 internal constant VAULT1 = bytes32(uint256(0x01));

    /// Deposit `amount` whole units of the order's output token (iToken1) into
    /// `owner`'s output vault so the order's outputMax isn't clamped to zero.
    function _depositOutput(address owner, uint256 amount, bytes32 vaultId) internal {
        vm.mockCall(
            address(iToken1),
            abi.encodeWithSelector(IERC20.transferFrom.selector, owner, address(iRaindex)),
            abi.encode(true)
        );
        vm.prank(owner);
        iRaindex.deposit4(address(iToken1), vaultId, LibDecimalFloat.packLossless(int256(amount), 0), new TaskV2[](0));
    }

    /// Add an order owned by `owner` with input=iToken0(vaultId), output=iToken1(vaultId).
    function _order(address owner, bytes memory expr, bytes32 vaultId) internal returns (OrderV4 memory) {
        return
            LibTestTakeOrder.addOrderWithExpression(
                vm, owner, expr, address(iToken0), vaultId, address(iToken1), vaultId
            );
    }

    function _order(address owner, bytes memory expr) internal returns (OrderV4 memory) {
        return _order(owner, expr, VAULT1);
    }

    /// Mock the taker token transfers so a successful fill doesn't revert:
    /// taker receives iToken1 (transfer), taker pays iToken0 (transferFrom).
    function _mockTakerTransfers() internal {
        vm.mockCall(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector), abi.encode(true));
        vm.mockCall(address(iToken0), abi.encodeWithSelector(IERC20.transferFrom.selector), abi.encode(true));
    }

    function _config(OrderV4 memory order) internal pure returns (TakeOrdersConfigV5 memory) {
        return LibTestTakeOrder.defaultTakeConfig(LibTestTakeOrder.wrapSingle(order));
    }

    /// Add an order with distinct internal input/output vaults so both vault
    /// legs are observable via vaultBalance2: input=iToken0(inVault),
    /// output=iToken1(outVault).
    function _orderDistinctVaults(address owner, bytes memory expr, bytes32 inVault, bytes32 outVault)
        internal
        returns (OrderV4 memory)
    {
        return LibTestTakeOrder.addOrderWithExpression(
            vm, owner, expr, address(iToken0), inVault, address(iToken1), outVault
        );
    }

    // ---------------------------------------------------------------------
    // B15/B16/B22/B23/B33/B36: market-buy (IOIsInput=true) arithmetic + token
    // routing. Order outputMax=5, ratio=2. maximumIO(input)=3 caps the take.
    // takerInput = min(5,3) = 3; takerOutput = ratio*input = 2*3 = 6.
    // Taker RECEIVES 3 iToken1 (transfer), PAYS 6 iToken0 (transferFrom).
    // ---------------------------------------------------------------------
    function testMarketBuyArithmeticAndRouting() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:5 2;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(3, 0);

        // Taker receives exactly 3 iToken1 (totalTakerInput).
        vm.mockCall(
            address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector, bob, uint256(3e18)), abi.encode(true)
        );
        vm.expectCall(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector, bob, uint256(3e18)), 1);
        // Taker pays exactly 6 iToken0 (totalTakerOutput).
        vm.mockCall(
            address(iToken0),
            abi.encodeWithSelector(IERC20.transferFrom.selector, bob, address(iRaindex), uint256(6e18)),
            abi.encode(true)
        );
        vm.expectCall(
            address(iToken0),
            abi.encodeWithSelector(IERC20.transferFrom.selector, bob, address(iRaindex), uint256(6e18)),
            1
        );

        vm.prank(bob);
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(3, 0)), "taker input == 3");
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(6, 0)), "taker output == 6");
    }

    // ---------------------------------------------------------------------
    // B15: takerInput = min(outputMax, remainingTakerIO). Here outputMax=2 is
    // SMALLER than maximumIO=100, so the take is bounded by outputMax (=2), not
    // the taker limit. ratio=1 => output=2. Pins that the cap is a MIN: a
    // mutation dropping the min (using remainingTakerIO=100) would give 100.
    // ---------------------------------------------------------------------
    function testMarketBuyBoundedByOutputMaxNotTakerLimit() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:2 1;:;");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(100, 0);

        vm.prank(bob);
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(2, 0)), "taker input == 2 (outputMax)");
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(2, 0)), "taker output == 2");
    }

    // ---------------------------------------------------------------------
    // B18/B19/B20/B21: market-sell (IOIsInput=false). Order outputMax=10,
    // ratio=0.5. orderMaxInput = ratio*outputMax = 0.5*10 = 5. maximumIO
    // (output) = 2 caps: takerOutput = min(5,2) = 2. takerInput = output/ratio
    // = 2/0.5 = 4. Taker receives 4 iToken1, pays 2 iToken0.
    // ---------------------------------------------------------------------
    function testMarketSellArithmeticAndRouting() external {
        _depositOutput(alice, 20, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:10 0.5;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = false;
        config.maximumIO = LibDecimalFloat.packLossless(2, 0);

        // Taker receives exactly 4 iToken1.
        vm.mockCall(
            address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector, bob, uint256(4e18)), abi.encode(true)
        );
        vm.expectCall(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector, bob, uint256(4e18)), 1);
        // Taker pays exactly 2 iToken0.
        vm.mockCall(
            address(iToken0),
            abi.encodeWithSelector(IERC20.transferFrom.selector, bob, address(iRaindex), uint256(2e18)),
            abi.encode(true)
        );
        vm.expectCall(
            address(iToken0),
            abi.encodeWithSelector(IERC20.transferFrom.selector, bob, address(iRaindex), uint256(2e18)),
            1
        );

        vm.prank(bob);
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(4, 0)), "taker input == 4");
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(2, 0)), "taker output == 2");
    }

    // ---------------------------------------------------------------------
    // B19: takerOutput = min(orderMaxInput, remainingTakerIO). Here orderMaxInput
    // = ratio*outputMax = 0.5*10 = 5 is SMALLER than maximumIO=100, so the take
    // is bounded by the order (output 5), not the taker limit. input = 5/0.5 =10.
    // ---------------------------------------------------------------------
    function testMarketSellBoundedByOrderNotTakerLimit() external {
        _depositOutput(alice, 20, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:10 0.5;:;");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = false;
        config.maximumIO = LibDecimalFloat.packLossless(100, 0);

        vm.prank(bob);
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(10, 0)), "taker input == 10");
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(5, 0)), "taker output == 5 (orderMaxInput)");
    }

    // ---------------------------------------------------------------------
    // B10/B13: IORatio > maximumIORatio => skip with OrderExceedsMaxRatio, NO
    // fill, returns zero/zero. Order ratio=100, maximumIORatio=1.
    // ---------------------------------------------------------------------
    function testExceedsMaxRatioSkips() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:1 100;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        config.maximumIORatio = LibDecimalFloat.packLossless(1, 0);

        // No token should move on a skip.
        vm.mockCallRevert(address(iToken0), abi.encodeWithSelector(IERC20.transfer.selector), "no iToken0.transfer");
        vm.mockCallRevert(
            address(iToken0), abi.encodeWithSelector(IERC20.transferFrom.selector), "no iToken0.transferFrom"
        );
        vm.mockCallRevert(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector), "no iToken1.transfer");

        vm.prank(bob);
        vm.expectEmit(true, true, true, true);
        emit IRaindexV6.OrderExceedsMaxRatio(bob, alice, LibOrder.hash(order));
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.isZero(), "input zero");
        assertTrue(totalTakerOutput.isZero(), "output zero");
    }

    // ---------------------------------------------------------------------
    // B10 boundary: ratio EXACTLY equal to maximumIORatio is NOT a skip (the
    // guard is strict `>`). ratio=2, maximumIORatio=2 => order fills.
    // Pins `>` vs `>=`: a `>=` mutation would skip an exactly-equal ratio.
    // ---------------------------------------------------------------------
    function testRatioEqualToMaxIsTaken() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:1 2;:;");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(1, 0);
        config.maximumIORatio = LibDecimalFloat.packLossless(2, 0);

        vm.prank(bob);
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        // outputMax=1, ratio=2: takerInput=min(1,1)=1, takerOutput=2.
        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(1, 0)), "input 1 (ratio==max is taken)");
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(2, 0)), "output 2");
    }

    // ---------------------------------------------------------------------
    // B11: outputMax == 0 => skip with OrderZeroAmount (ratio is fine).
    // ---------------------------------------------------------------------
    function testZeroOutputMaxSkips() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:0 1;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        vm.mockCallRevert(address(iToken0), abi.encodeWithSelector(IERC20.transfer.selector), "no transfer");
        vm.mockCallRevert(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector), "no transfer");

        vm.prank(bob);
        vm.expectEmit(true, true, true, true);
        emit IRaindexV6.OrderZeroAmount(bob, alice, LibOrder.hash(order));
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.isZero(), "input zero");
        assertTrue(totalTakerOutput.isZero(), "output zero");
    }

    // ---------------------------------------------------------------------
    // B12: ratio == 0 (with positive outputMax, within maxRatio) => skip with
    // OrderZeroAmount. Pins the `!IORatio.gt(0)` half of the zero-amount guard.
    // ---------------------------------------------------------------------
    function testZeroRatioSkips() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:5 0;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        vm.mockCallRevert(address(iToken0), abi.encodeWithSelector(IERC20.transfer.selector), "no transfer");
        vm.mockCallRevert(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector), "no transfer");

        vm.prank(bob);
        vm.expectEmit(true, true, true, true);
        emit IRaindexV6.OrderZeroAmount(bob, alice, LibOrder.hash(order));
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.isZero(), "input zero");
        assertTrue(totalTakerOutput.isZero(), "output zero");
    }

    // ---------------------------------------------------------------------
    // B13: ordering of guards. An order whose ratio exceeds the max AND has zero
    // output must emit OrderExceedsMaxRatio (ratio checked FIRST), NOT
    // OrderZeroAmount. ratio=100 > maximumIORatio=1, outputMax=0.
    // ---------------------------------------------------------------------
    function testRatioCheckedBeforeZeroAmount() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:0 100;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        config.maximumIORatio = LibDecimalFloat.packLossless(1, 0);

        vm.prank(bob);
        vm.recordLogs();
        iRaindex.takeOrders4(config);
        Vm.Log[] memory logs = vm.getRecordedLogs();
        assertEq(logs.length, 1, "exactly one skip event");
        assertEq(
            logs[0].topics[0],
            bytes32(uint256(keccak256("OrderExceedsMaxRatio(address,address,bytes32)"))),
            "ratio checked before zero amount"
        );
    }

    // ---------------------------------------------------------------------
    // B8: an order whose input token equals its output token reverts
    // TokenSelfTrade (checked per order inside the loop, after the token-mismatch
    // guard). Both validInputs[0] and validOutputs[0] are iToken1 so the batch
    // io tokens match (no TokenMismatch) and the self-trade guard is reached.
    // ---------------------------------------------------------------------
    function testSelfTradeReverts() external {
        OrderV4 memory order = LibTestTakeOrder.addOrderWithExpression(
            vm, alice, "_ _:5 1;:;", address(iToken1), VAULT1, address(iToken1), VAULT1
        );

        TakeOrdersConfigV5 memory config = _config(order);
        config.maximumIO = LibDecimalFloat.packLossless(5, 0);

        vm.prank(bob);
        // selector for TokenSelfTrade() is the src-level error.
        vm.expectRevert(bytes4(keccak256("TokenSelfTrade()")));
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B1: empty orders array reverts NoOrders.
    // ---------------------------------------------------------------------
    function testNoOrdersReverts() external {
        TakeOrdersConfigV5 memory config = TakeOrdersConfigV5({
            minimumIO: LibDecimalFloat.packLossless(0, 0),
            maximumIO: LibDecimalFloat.packLossless(1, 0),
            maximumIORatio: LibDecimalFloat.packLossless(1, 0),
            IOIsInput: true,
            orders: new TakeOrderConfigV4[](0),
            data: ""
        });
        vm.prank(bob);
        vm.expectRevert(IRaindexV6.NoOrders.selector);
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B4: maximumIO == 0 reverts ZeroMaximumIO (checked before the loop). A
    // single live, fillable order is present so the revert is purely the
    // zero-max guard, not an empty batch.
    // ---------------------------------------------------------------------
    function testZeroMaximumIOReverts() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:5 1;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        config.maximumIO = LibDecimalFloat.packLossless(0, 0);

        vm.prank(bob);
        vm.expectRevert(IRaindexV6.ZeroMaximumIO.selector);
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B4 boundary: a NEGATIVE maximumIO also reverts ZeroMaximumIO (guard is
    // `!maximumIO.gt(0)`, i.e. <= 0). Pins the `gt` predicate against a `ge`
    // mutation (which would let 0 through) and a negation flip.
    // ---------------------------------------------------------------------
    function testNegativeMaximumIOReverts() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:5 1;:;");

        TakeOrdersConfigV5 memory config = _config(order);
        config.maximumIO = LibDecimalFloat.packLossless(-1, 0);

        vm.prank(bob);
        vm.expectRevert(IRaindexV6.ZeroMaximumIO.selector);
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B6: input token mismatch reverts TokenMismatch. The batch's input token is
    // fixed from orders[0]; a second order with a different input token reverts.
    // ---------------------------------------------------------------------
    function testInputTokenMismatchReverts() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order0 = _order(alice, "_ _:5 1;:;");
        // order1 has input token iToken1 (mismatch vs io.inputToken == iToken0).
        OrderV4 memory order1 = LibTestTakeOrder.addOrderWithExpression(
            vm, alice, "_ _:5 1;:;", address(iToken1), VAULT1, address(iToken1), VAULT1
        );

        TakeOrderConfigV4[] memory orders = new TakeOrderConfigV4[](2);
        orders[0] = TakeOrderConfigV4(order0, 0, 0, new SignedContextV1[](0));
        orders[1] = TakeOrderConfigV4(order1, 0, 0, new SignedContextV1[](0));
        TakeOrdersConfigV5 memory config = LibTestTakeOrder.defaultTakeConfig(orders);
        config.maximumIO = LibDecimalFloat.packLossless(100, 0);

        _mockTakerTransfers();
        vm.prank(bob);
        vm.expectRevert(TokenMismatch.selector);
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B7: output token mismatch reverts TokenMismatch.
    // ---------------------------------------------------------------------
    function testOutputTokenMismatchReverts() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order0 = _order(alice, "_ _:5 1;:;");
        // order1 output token iToken0 (mismatch vs io.outputToken == iToken1).
        OrderV4 memory order1 = LibTestTakeOrder.addOrderWithExpression(
            vm, alice, "_ _:5 1;:;", address(iToken0), VAULT1, address(iToken0), VAULT1
        );

        TakeOrderConfigV4[] memory orders = new TakeOrderConfigV4[](2);
        orders[0] = TakeOrderConfigV4(order0, 0, 0, new SignedContextV1[](0));
        orders[1] = TakeOrderConfigV4(order1, 0, 0, new SignedContextV1[](0));
        TakeOrdersConfigV5 memory config = LibTestTakeOrder.defaultTakeConfig(orders);
        config.maximumIO = LibDecimalFloat.packLossless(100, 0);

        _mockTakerTransfers();
        vm.prank(bob);
        vm.expectRevert(TokenMismatch.selector);
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B32: MinimumIO. With IOIsInput=true the relevant quantity is the taker
    // INPUT. Order outputMax=1e-18, ratio=1, minimumIO=1. actual input is 1e-18
    // which is < 1 => revert MinimumIO(1, 1e-18). Pins both the comparison and
    // the (minimumIO, actualIO) argument values.
    // ---------------------------------------------------------------------
    function testMinimumIOInputRevert() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:1e-18 1;:;");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.minimumIO = LibDecimalFloat.packLossless(1, 0);

        vm.prank(bob);
        vm.expectRevert(
            abi.encodeWithSelector(
                MinimumIO.selector, LibDecimalFloat.packLossless(1, 0), LibDecimalFloat.packLossless(1, -18)
            )
        );
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B32 boundary: actual EXACTLY equal to minimumIO does NOT revert (guard is
    // strict `<`). outputMax=1, ratio=1, minimumIO=1, take input = 1. Pins `<`
    // vs `<=`: a `<=` mutation would revert on the exact-equal case.
    // ---------------------------------------------------------------------
    function testMinimumIOExactlyMetFills() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:1 1;:;");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(1, 0);
        config.minimumIO = LibDecimalFloat.packLossless(1, 0);

        vm.prank(bob);
        (Float totalTakerInput,) = iRaindex.takeOrders4(config);
        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(1, 0)), "input == minimumIO fills");
    }

    // ---------------------------------------------------------------------
    // B31: with IOIsInput=true the MinimumIO check compares against the taker
    // INPUT, not the output. Order outputMax=1, ratio=3, maximumIO(input)=1 =>
    // takerInput=1, takerOutput=3. minimumIO=2 sits between input(1) and
    // output(3). The relevant quantity is the input (1 < 2) so the take MUST
    // revert MinimumIO(2, 1). If the selector wrongly used the output (3 >= 2)
    // the take would fill — so the revert + reported actual==1 pins the input
    // branch (distinct from the existing output-branch test).
    // ---------------------------------------------------------------------
    function testMinimumIOInputBranchSelectsInput() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:1 3;:;");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(1, 0);
        config.minimumIO = LibDecimalFloat.packLossless(2, 0);

        vm.prank(bob);
        vm.expectRevert(
            abi.encodeWithSelector(
                MinimumIO.selector, LibDecimalFloat.packLossless(2, 0), LibDecimalFloat.packLossless(1, 0)
            )
        );
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B9: a removed (dead) order is skipped with OrderNotFound, no fill, returns
    // zero/zero. Add then remove the order so sOrders[hash] == ORDER_DEAD.
    // ---------------------------------------------------------------------
    function testRemovedOrderEmitsOrderNotFound() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:5 1;:;");
        vm.prank(alice);
        iRaindex.removeOrder3(order, new TaskV2[](0));

        TakeOrdersConfigV5 memory config = _config(order);
        vm.mockCallRevert(address(iToken0), abi.encodeWithSelector(IERC20.transfer.selector), "no transfer");
        vm.mockCallRevert(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector), "no transfer");

        vm.prank(bob);
        vm.recordLogs();
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);
        Vm.Log[] memory logs = vm.getRecordedLogs();
        assertEq(logs.length, 1, "exactly one event");
        assertEq(
            logs[0].topics[0],
            bytes32(uint256(keccak256("OrderNotFound(address,address,bytes32)"))),
            "OrderNotFound emitted for dead order"
        );
        (address sender, address owner, bytes32 orderHash) = abi.decode(logs[0].data, (address, address, bytes32));
        assertEq(sender, bob, "OrderNotFound sender");
        assertEq(owner, alice, "OrderNotFound owner");
        assertEq(orderHash, LibOrder.hash(order), "OrderNotFound orderHash");
        assertTrue(totalTakerInput.isZero(), "input zero");
        assertTrue(totalTakerOutput.isZero(), "output zero");
    }

    // ---------------------------------------------------------------------
    // B26: TakeOrderV3 is emitted on a successful fill with the taker's input
    // and output. Order outputMax=3, ratio=2, max input 3 => input 3, output 6.
    // ---------------------------------------------------------------------
    function testTakeOrderV3EmittedWithAmounts() external {
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:3 2;:;");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(3, 0);

        TakeOrderConfigV4 memory expectedConfig = TakeOrderConfigV4(order, 0, 0, new SignedContextV1[](0));
        vm.prank(bob);
        vm.expectEmit(address(iRaindex));
        emit IRaindexV6.TakeOrderV3(
            bob, expectedConfig, LibDecimalFloat.packLossless(3, 0), LibDecimalFloat.packLossless(6, 0)
        );
        iRaindex.takeOrders4(config);
    }

    // ---------------------------------------------------------------------
    // B14/B29/B34/B35: callback gate. With non-empty data AND an order taken,
    // onTakeOrders2 fires exactly once with (outputToken=iToken1, inputToken
    // =iToken0, takerInput, takerOutput, data). Order outputMax=4, ratio=2, max
    // input 4 => takerInput 4, takerOutput 8. takerInput != takerOutput so the
    // callback amount args are distinguishable (pins B35 amount ordering).
    // ---------------------------------------------------------------------
    function testCallbackFiresWhenTakenWithArgs() external {
        RecordingTaker taker = new RecordingTaker(iRaindex);
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:4 2;:;");

        // taker (the contract) receives iToken1 and pays iToken0.
        vm.mockCall(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector), abi.encode(true));
        vm.mockCall(address(iToken0), abi.encodeWithSelector(IERC20.transferFrom.selector), abi.encode(true));

        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(4, 0);
        config.data = hex"abcd";

        taker.take(config);

        assertEq(taker.calls(), 1, "callback fired exactly once");
        assertEq(taker.lastOutputToken(), address(iToken1), "outputToken == iToken1");
        assertEq(taker.lastInputToken(), address(iToken0), "inputToken == iToken0");
        // takerInput (4, what taker receives) != takerOutput (8, what taker pays):
        // a swapped callback would report 8 and 4 respectively.
        assertTrue(taker.lastTakerInput().eq(LibDecimalFloat.packLossless(4, 0)), "callback takerInput == 4");
        assertTrue(taker.lastTakerOutput().eq(LibDecimalFloat.packLossless(8, 0)), "callback takerOutput == 8");
        assertEq(taker.lastData(), hex"abcd", "callback data");
    }

    // ---------------------------------------------------------------------
    // B34: callback gated on data.length>0. With an order taken but EMPTY data
    // the callback must NOT fire. Pins the data.length predicate.
    // ---------------------------------------------------------------------
    function testCallbackNotFiredWhenDataEmpty() external {
        RecordingTaker taker = new RecordingTaker(iRaindex);
        _depositOutput(alice, 10, VAULT1);
        OrderV4 memory order = _order(alice, "_ _:4 1;:;");

        vm.mockCall(address(iToken1), abi.encodeWithSelector(IERC20.transfer.selector), abi.encode(true));
        vm.mockCall(address(iToken0), abi.encodeWithSelector(IERC20.transferFrom.selector), abi.encode(true));

        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(4, 0);
        config.data = ""; // empty

        taker.take(config);
        assertEq(taker.calls(), 0, "callback must not fire with empty data");
    }

    // ---------------------------------------------------------------------
    // B29/B34: callback gated on ordersTaken. With non-empty data but the only
    // order SKIPPED (zero output), the callback must NOT fire. Pins the
    // ordersTaken half of the gate independently of data.length.
    // ---------------------------------------------------------------------
    function testCallbackNotFiredWhenNothingTaken() external {
        RecordingTaker taker = new RecordingTaker(iRaindex);
        OrderV4 memory order = _order(alice, "_ _:0 1;:;"); // zero output => skip

        TakeOrdersConfigV5 memory config = _config(order);
        config.data = hex"abcd"; // non-empty
        config.minimumIO = LibDecimalFloat.packLossless(0, 0);

        taker.take(config);
        assertEq(taker.calls(), 0, "callback must not fire when nothing taken");
    }

    // ---------------------------------------------------------------------
    // B22/B23/B27/B28/B30: batch accumulation across two takeable orders. Order
    // A outputMax=3, order C outputMax=5 (DISTINCT so the total uniquely
    // discriminates ADD from ASSIGN). ratio=1; maximumIO(input)=20 lets both
    // fill fully. totals == 3+5 == 8: a mutation that ASSIGNS instead of adds
    // gives 5 (the last), one that stops the loop early gives 3, one that drops
    // the second handle gives a wrong vault movement. Both TakeOrderV3 events
    // fire (one per filled order).
    // ---------------------------------------------------------------------
    function testBatchAccumulatesTwoOrders() external {
        _depositOutput(alice, 10, VAULT1);
        _depositOutput(carol, 10, VAULT1);
        OrderV4 memory orderA = _order(alice, "_ _:3 1;:;");
        OrderV4 memory orderC = _order(carol, "_ _:5 1;:;");

        TakeOrderConfigV4[] memory orders = new TakeOrderConfigV4[](2);
        orders[0] = TakeOrderConfigV4(orderA, 0, 0, new SignedContextV1[](0));
        orders[1] = TakeOrderConfigV4(orderC, 0, 0, new SignedContextV1[](0));
        TakeOrdersConfigV5 memory config = LibTestTakeOrder.defaultTakeConfig(orders);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(20, 0);

        _mockTakerTransfers();
        vm.prank(bob);
        vm.recordLogs();
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);

        assertTrue(
            totalTakerInput.eq(LibDecimalFloat.packLossless(8, 0)), "total input == 3+5 == 8 (added, not assigned)"
        );
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(8, 0)), "total output == 8");

        // Exactly two TakeOrderV3 events (one per filled order).
        assertEq(_countTakeOrderV3(vm.getRecordedLogs()), 2, "both orders emit TakeOrderV3");

        // Both owners' output vaults were debited by their fill (alice 3, carol
        // 5): pins that BOTH orders' recordVaultOutput + handleIO ran, not just
        // the last. 10 deposited - fill.
        assertTrue(
            iRaindex.vaultBalance2(alice, address(iToken1), VAULT1).eq(LibDecimalFloat.packLossless(7, 0)),
            "alice output vault debited by 3"
        );
        assertTrue(
            iRaindex.vaultBalance2(carol, address(iToken1), VAULT1).eq(LibDecimalFloat.packLossless(5, 0)),
            "carol output vault debited by 5"
        );
    }

    // ---------------------------------------------------------------------
    // B5/B17: the loop stops once remainingTakerIO is exhausted. Order A
    // outputMax=3, order C outputMax=5; maximumIO(input)=3 fills the FIRST
    // order fully (3) and leaves nothing, so the SECOND (5) does NOT fill: total
    // input == 3 (not 5, not 8), exactly ONE TakeOrderV3. Pins the loop guard
    // `remainingTakerIO.gt(0)` and the remaining decrement.
    // ---------------------------------------------------------------------
    function testLoopStopsWhenTakerExhausted() external {
        _depositOutput(alice, 10, VAULT1);
        _depositOutput(carol, 10, VAULT1);
        OrderV4 memory orderA = _order(alice, "_ _:3 1;:;");
        OrderV4 memory orderC = _order(carol, "_ _:5 1;:;");

        TakeOrderConfigV4[] memory orders = new TakeOrderConfigV4[](2);
        orders[0] = TakeOrderConfigV4(orderA, 0, 0, new SignedContextV1[](0));
        orders[1] = TakeOrderConfigV4(orderC, 0, 0, new SignedContextV1[](0));
        TakeOrdersConfigV5 memory config = LibTestTakeOrder.defaultTakeConfig(orders);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(3, 0);

        _mockTakerTransfers();
        vm.prank(bob);
        vm.recordLogs();
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);

        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(3, 0)), "total input capped at 3 (only first fills)");
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(3, 0)), "total output == 3");

        assertEq(_countTakeOrderV3(vm.getRecordedLogs()), 1, "only the first order fills; loop stops when exhausted");
    }

    // ---------------------------------------------------------------------
    // B17: market-buy decrements remainingTakerIO by the taker INPUT (not the
    // output). With ratio=2 (output != input) this is observable across orders.
    // Two orders, each outputMax=3 ratio=2, maximumIO(input)=5.
    //   A: takerInput = min(3,5)=3, takerOutput=2*3=6, remaining -= 3 => 2.
    //   C: takerInput = min(3,2)=2, takerOutput=2*2=4, remaining -= 2 => 0.
    //   totals: input = 3+2 = 5, output = 6+4 = 10.
    // A mutation decrementing by takerOutput (6) instead drives remaining to -1
    // after A, so the loop stops and C is skipped: totals input=3, output=6.
    // ---------------------------------------------------------------------
    function testMarketBuyRemainingDecrementsByInput() external {
        _depositOutput(alice, 10, VAULT1);
        _depositOutput(carol, 10, VAULT1);
        OrderV4 memory orderA = _order(alice, "_ _:3 2;:;");
        OrderV4 memory orderC = _order(carol, "_ _:3 2;:;");

        TakeOrderConfigV4[] memory orders = new TakeOrderConfigV4[](2);
        orders[0] = TakeOrderConfigV4(orderA, 0, 0, new SignedContextV1[](0));
        orders[1] = TakeOrderConfigV4(orderC, 0, 0, new SignedContextV1[](0));
        TakeOrdersConfigV5 memory config = LibTestTakeOrder.defaultTakeConfig(orders);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(5, 0);

        _mockTakerTransfers();
        vm.prank(bob);
        vm.recordLogs();
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);

        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(5, 0)), "total input == 3+2 == 5");
        assertTrue(totalTakerOutput.eq(LibDecimalFloat.packLossless(10, 0)), "total output == 6+4 == 10");
        // Both orders filled, proving remaining was decremented by input not output.
        assertEq(_countTakeOrderV3(vm.getRecordedLogs()), 2, "both orders fill (remaining tracks input)");
    }

    // ---------------------------------------------------------------------
    // B24: the OUTPUT vault leg debits the order owner's output vault by the
    // taker INPUT (= the order's output amount). With ratio=2 (input != output)
    // the leg is observable. outputMax=3, ratio=2, maximumIO(input)=3 =>
    // takerInput=3, takerOutput=6. Output vault (iToken1) starts 10, ends 7.
    // A mutation debiting by takerOutput (6) ends the vault at 4 instead.
    // ---------------------------------------------------------------------
    function testOutputVaultLegDebitedByTakerInput() external {
        bytes32 inVault = bytes32(uint256(0x02));
        bytes32 outVault = VAULT1;
        _depositOutput(alice, 10, outVault);
        OrderV4 memory order = _orderDistinctVaults(alice, "_ _:3 2;:;", inVault, outVault);

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(3, 0);

        vm.prank(bob);
        iRaindex.takeOrders4(config);

        // Output vault debited by takerInput == 3 (not takerOutput == 6): 10-3=7.
        assertTrue(
            iRaindex.vaultBalance2(alice, address(iToken1), outVault).eq(LibDecimalFloat.packLossless(7, 0)),
            "output vault debited by takerInput (3), not takerOutput (6)"
        );
    }

    // ---------------------------------------------------------------------
    // B25: the INPUT vault leg credits the order owner's input vault by the
    // taker OUTPUT (= the order's input amount). outputMax=3, ratio=2,
    // maximumIO(input)=3 => takerOutput=6. Input vault (iToken0, internal)
    // starts 0, ends 6. A mutation crediting by takerInput (3) ends it at 3.
    // ---------------------------------------------------------------------
    function testInputVaultLegCreditedByTakerOutput() external {
        bytes32 inVault = bytes32(uint256(0x02));
        bytes32 outVault = VAULT1;
        _depositOutput(alice, 10, outVault);
        OrderV4 memory order = _orderDistinctVaults(alice, "_ _:3 2;:;", inVault, outVault);

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(3, 0);

        vm.prank(bob);
        iRaindex.takeOrders4(config);

        // Input vault credited by takerOutput == 6 (not takerInput == 3).
        assertTrue(
            iRaindex.vaultBalance2(alice, address(iToken0), inVault).eq(LibDecimalFloat.packLossless(6, 0)),
            "input vault credited by takerOutput (6), not takerInput (3)"
        );
    }

    // ---------------------------------------------------------------------
    // B21: market-sell decrements remainingTakerIO by the taker OUTPUT (not the
    // input). With ratio=2, output != input, observable across orders. Two
    // orders, each outputMax=10 ratio=2, maximumIO(output)=6.
    //   orderMaxInput = 2*10 = 20.
    //   A: takerOutput = min(20,6)=6, takerInput = 6/2 = 3, remaining -= 6 => 0.
    //   loop stops; B does NOT fill. totals: output=6, input=3.
    // A mutation decrementing by takerInput (3) leaves remaining = 3 > 0, so
    // order B ALSO fills (takerOutput=3, takerInput=1.5): totals output=9,
    // input=4.5 — a different observable result.
    // ---------------------------------------------------------------------
    function testMarketSellRemainingDecrementsByOutput() external {
        _depositOutput(alice, 20, VAULT1);
        _depositOutput(carol, 20, VAULT1);
        OrderV4 memory orderA = _order(alice, "_ _:10 2;:;");
        OrderV4 memory orderC = _order(carol, "_ _:10 2;:;");

        TakeOrderConfigV4[] memory orders = new TakeOrderConfigV4[](2);
        orders[0] = TakeOrderConfigV4(orderA, 0, 0, new SignedContextV1[](0));
        orders[1] = TakeOrderConfigV4(orderC, 0, 0, new SignedContextV1[](0));
        TakeOrdersConfigV5 memory config = LibTestTakeOrder.defaultTakeConfig(orders);
        config.IOIsInput = false;
        config.maximumIO = LibDecimalFloat.packLossless(6, 0);

        _mockTakerTransfers();
        vm.prank(bob);
        vm.recordLogs();
        (Float totalTakerInput, Float totalTakerOutput) = iRaindex.takeOrders4(config);

        assertTrue(
            totalTakerOutput.eq(LibDecimalFloat.packLossless(6, 0)), "total output capped at 6 (only first fills)"
        );
        assertTrue(totalTakerInput.eq(LibDecimalFloat.packLossless(3, 0)), "total input == 6/2 == 3");
        assertEq(_countTakeOrderV3(vm.getRecordedLogs()), 1, "only first order fills (remaining tracks output)");
    }

    // ---------------------------------------------------------------------
    // B28: handleIO runs the order's handle-IO entrypoint per taken order. An
    // order whose handle-IO source REVERTS must revert the whole take when the
    // order is taken. A mutation that drops the handleIO call lets the take
    // succeed (no revert), so the revert proves handleIO ran. The handle-IO
    // source `:ensure(0 "ho");` always reverts on evaluation.
    // ---------------------------------------------------------------------
    function testHandleIORunsPerTakenOrder() external {
        _depositOutput(alice, 10, VAULT1);
        // calculate: outputMax=5 ratio=1; handle-io: ensure(0) reverts.
        OrderV4 memory order = _order(alice, "_ _:5 1;:ensure(0 \"handleio ran\");");

        _mockTakerTransfers();
        TakeOrdersConfigV5 memory config = _config(order);
        config.IOIsInput = true;
        config.maximumIO = LibDecimalFloat.packLossless(5, 0);

        vm.prank(bob);
        vm.expectRevert(bytes("handleio ran"));
        iRaindex.takeOrders4(config);
    }

    /// Count TakeOrderV3 events in the recorded logs. The topic is the keccak of
    /// the fully-expanded event signature (TakeOrderConfigV4 -> OrderV4 ->
    /// EvaluableV4/IOV2[]/SignedContextV1[]; Float is a `bytes32` user type, so
    /// the two trailing input/output args canonicalize to `bytes32`).
    function _countTakeOrderV3(Vm.Log[] memory logs) internal pure returns (uint256 count) {
        bytes32 takeSig = keccak256(
            "TakeOrderV3(address,((address,(address,address,bytes),(address,bytes32)[],(address,bytes32)[],bytes32),uint256,uint256,(address,bytes32[],bytes)[]),bytes32,bytes32)"
        );
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics.length > 0 && logs[i].topics[0] == takeSig) {
                count++;
            }
        }
    }
}
