SELECT COUNT(*) AS trade_count
FROM derived_trades tws
WHERE 1 = 1
/*CHAIN_IDS_CLAUSE*/
/*RAINDEXES_CLAUSE*/
/*TAKERS_CLAUSE*/
/*OWNERS_CLAUSE*/
/*ORDER_HASH_CLAUSE*/
/*ORDER_HASHES_CLAUSE*/
/*START_TS_CLAUSE*/
/*END_TS_CLAUSE*/
/*INPUT_TOKENS_CLAUSE*/
/*OUTPUT_TOKENS_CLAUSE*/;
