name: Manual sol artifacts
on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Suite to deploy"
        required: true
        type: choice
        options:
          - raindex
          - subparser
          - route-processor
          - arb-generic-pool-order-taker
          - arb-route-processor-order-taker
          - arb-generic-pool-flash-borrower
jobs:
  deploy:
    uses: rainlanguage/rainix/.github/workflows/rainix-manual-sol-artifacts.yaml@main
    with:
      suite: ${{ inputs.suite }}
    secrets: inherit
